"""empty message

Revision ID: 039cea215892
Revises: 6e98cbe25501
Create Date: 2018-06-26 14:55:02.504005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039cea215892'
down_revision = '6e98cbe25501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_item', sa.Column('done_flag', sa.Boolean(), nullable=True))
    op.add_column('todo_item', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_item', 'due_date')
    op.drop_column('todo_item', 'done_flag')
    # ### end Alembic commands ###
